### ISSUE TITLE
Kata: Terminal Hero

### ISSUE THREAD

**Issue by codingbootcampseu** [GagaSissi/bootcamp-schedule#13]
This kata requires some knowledge about terminal commands such as creating, deleting and moving files and folders. Follow the instructions below and validate the result with the last step (which is a script that validates your work).

- [x] Go to your home folder
- [x] Create a new folder called `terminal-hero` and go to the newly created folder
- [x] Create a new empty file called `test.md`
- [x] Echo the text `hero of the terminal` into the `test.md` file
- [x] Create a new folder (you are still in your `terminal-hero` folder) that is named like your first name
  - Please use lower casing and replace possible german Umlaute
- [x] Create a new folder (you are still in the `terminal-hero` folder) that is called `anti-hero`
- [x] Move the `test.md` file to the `anti-hero` folder
- [x] Use the cat command to output the contents of the `anti-hero/test.md` file and redirect it into a new file called `hero.md` in the `terminal-hero` folder
- [x] Move the `hero.md` into the first name folder
- [x] Delete the `anti-hero` folder
- [x] Navigate back into the terminal-hero folder (just in case if you are somewhere else)
- [x] Execute this command `bash <(curl -s https://raw.githubusercontent.com/coding-bootcamps-eu/terminal-hero/main/terminal-hero.sh)`

> Watch the output 😎

**Comment by GagaSissi** [comment]
I had one big letter in it, so the popup was not quite perfect.
