### ISSUE TITLE
Intro to Programming with P5: Comet

### ISSUE THREAD

**Issue by codingbootcampseu** [GagaSissi/bootcamp-schedule#57]
Start with a new p5 sketch.

- [x] Use a dark background
- [x] Draw a comet (circle) which moves from the top left corner to the bottom right corner
- [x] If the comet reaches the edge of the canvas it should start from the top left corner again
 
**Hints**

You can use global variables to save the current position of the comet which can be incremented in the `draw()` function.

```js
let posX = 0;

function draw() {
  circle(posX, 100, 30);
  posX = posX + 1;
}
```

**Bonus**

The comet should get bigger while it moves through the canvas.

The comet should have a fading tail.

**Example Solution**

- [Example solution](https://editor.p5js.org/CodingBootcampsEu/sketches/-5VqLsScn)

**Comment by GagaSissi** [comment]
let canvasEnd = 430;
let posX = 0;
let posY = 0;
let circleSize = 30;

function setup (){
  createCanvas (400, 400);
  background ("black");
}
// Einen Kometen zeichnen
function draw (){
  background (0, 0, 0, 10)
  circle (posX, posY, circleSize);
  fill ("white");
  noStroke ();
  
  //Ohne Schweif, wegen dem Rendering. Wenn kein background.
  //strokeWeight (10);
  
  posX = posX +1;
  posY = posY +1;
  circleSize +=0.1;
  
  
  if (posX > canvasEnd ) {
    posX = 0;
    posY = 0;
    //circleSize = 0;
    circleSize = 30;
  }
}
